"""add last_users to asset

Revision ID: a21fa5c11e29
Revises: 9ad583306e89
Create Date: 2025-07-15 16:10:00.279452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21fa5c11e29'
down_revision: Union[str, Sequence[str], None] = '9ad583306e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('last_users', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'last_users')
    # ### end Alembic commands ###
